export const SET_DISPLAY_SPORTS = 'SET_DISPLAY_SPORTS'
export const SET_DISPLAY_SPORTS_ERROR = 'SET_DISPLAY_SPORTS_ERROR'

export const SET_DISPLAY_MARKETING = 'SET_DISPLAY_MARKETING'
export const SET_DISPLAY_MARKETING_ERROR = 'SET_DISPLAY_MARKETING_ERROR'

export const SET_DISPLAY_ENVIRONMENT = 'SET_DISPLAY_ENVIRONMENT'
export const SET_DISPLAY_ENVIRONMENT_ERROR = 'SET_DISPLAY_ENVIRONMENT_ERROR'
